from __future__ import annotations

import hashlib
from copy import deepcopy
from typing import Any


def _source(
    key: str,
    label: str,
    summary: str,
    *facts: str,
    status: str = "verified",
    authority: str = "system_of_record",
    max_age_seconds: int = 2_592_000,
) -> dict[str, Any]:
    evidence_hash = hashlib.sha256(
        "|".join((key, label, summary, *facts)).encode("utf-8")
    ).hexdigest()
    return {
        "key": key,
        "label": label,
        "status": status,
        "summary": summary,
        "facts": list(facts),
        "authority": authority,
        "integrity": "sha256_verified",
        "integrity_hash": evidence_hash,
        "observed_at": "2026-08-16T18:00:00Z",
        "max_age_seconds": max_age_seconds,
        "conflicts": [],
    }


def _case(
    *,
    case_id: str,
    customer_id: str,
    customer: str,
    title: str,
    task_type: str,
    request: str,
    amount: float,
    expected_mode: str,
    permission_floor: str,
    priority: str,
    queue_status: str,
    customer_goal: str,
    business_guardrail: str,
    sources: list[dict[str, Any]],
    options: list[dict[str, Any]],
    reason: str,
    lesson: str,
    account_type: str = "standard",
    region: str = "US",
    contract_type: str = "retail_standard",
    fraud_signal: bool = False,
    safety_critical: bool = False,
    auto_cost_cap: float = 150.0,
    events: list[dict[str, Any]] | None = None,
    customer_segment: str = "consumer",
) -> dict[str, Any]:
    evidence_as_of = "2026-08-16T20:00:00Z"
    sourced_records = deepcopy(sources)
    for source in sourced_records:
        source["source_record_id"] = f"EV-{case_id}-{source['key']}"
        source["source_system"] = str(source["label"]).lower().replace(" ", "_")
        source["correlation"] = {
            "case_id": case_id,
            "customer_id": customer_id,
            "task_type": task_type,
        }
    required_sources = [source["key"] for source in sourced_records]
    prepared_options = deepcopy(options)
    for index, option in enumerate(prepared_options):
        action = str(option.get("action") or "deny")
        option.setdefault(
            "amount",
            _default_action_amount(
                action,
                float(option.get("customer_value", 0)),
                float(option.get("company_cost", 0)),
            ),
        )
        option.setdefault("goal_fit", 1.0)
        option.setdefault("eligible", True)
        option.setdefault("permission_floor", permission_floor)
        option.setdefault("auto_cost_cap", auto_cost_cap)
        option.setdefault("safety_critical", safety_critical)
        option.setdefault(
            "value_components",
            [
                {
                    "label": "Resolved customer value",
                    "amount": option.get("customer_value", 0),
                    "basis": "Case economics source",
                }
            ],
        )
        if index == 0:
            option.setdefault("reason", reason)
            option.setdefault("lesson", lesson)
    return {
        "case_id": case_id,
        "title": title,
        "queue_status": queue_status,
        "priority": priority,
        "customer": {
            "customer_id": customer_id,
            "display_name": customer,
            "account_type": account_type,
            "region": region,
            "contract_type": contract_type,
        },
        "task_type": task_type,
        "request_text": request,
        "requested_amount": amount,
        "existing_credit": 0.0,
        "fraud_signal": fraud_signal,
        "ground_truth_amount": prepared_options[0]["amount"],
        "expected_mode": expected_mode,
        "customer_segment": customer_segment,
        "evidence_as_of": evidence_as_of,
        "customer_goal": customer_goal,
        "business_guardrail": business_guardrail,
        "evidence_required": required_sources,
        "evidence_sources": sourced_records,
        "resolution_options": prepared_options,
        "resolution_constraints": {
            "default_permission_floor": permission_floor,
            "auto_cost_cap": auto_cost_cap,
            "safety_critical": safety_critical,
            "resolution_cost_cap": max(float(amount), float(auto_cost_cap)),
            "minimum_goal_fit": 0.0,
        },
        "events": events or [],
        "payments": [],
    }


def _default_action_amount(action: str, customer_value: float, company_cost: float) -> float:
    if action in {
        "deny",
        "guided_troubleshooting",
        "cost_containment",
        "rollback_deployment",
        "least_privilege_fix",
        "database_capacity_recovery",
        "traffic_stabilization",
        "security_containment",
        "isolated_restore",
        "quota_adjustment",
    }:
        return 0.0
    if action in {"partial_refund", "refund"}:
        return company_cost
    return customer_value


ANALYST_CASES: tuple[dict[str, Any], ...] = (
    _case(
        case_id="CASE-184-26",
        customer_id="C-184",
        customer="Srinivas",
        title="Cosmetic transit damage on a high-return espresso machine",
        task_type="damaged_item_keep_offer",
        request="My espresso machine arrived dented. It still works, but I do not want to pay full price for a damaged product.",
        amount=249,
        expected_mode="VERIFY",
        permission_floor="VERIFY",
        priority="NORMAL",
        queue_status="CUSTOMER_CHOICE",
        customer_goal="Receive fair value without waiting for a replacement.",
        business_guardrail="Ask before applying a keep-item discount; cap compensation below reverse-logistics plus refurbishment cost.",
        sources=[
            _source(
                "order",
                "Order record",
                "Delivered yesterday; $249 paid",
                "ORD-18421",
                "Espresso Pro E7",
                "Delivered 2026-08-15",
            ),
            _source(
                "damage_photo",
                "Damage inspection",
                "Photo classifier found a cosmetic side-panel dent",
                "No water-path damage",
                "Power-on video passes",
                "Confidence 98.2%",
            ),
            _source(
                "customer_history",
                "Customer history",
                "18 orders in 4 years with one prior return",
                "Claim rate 5.6%",
                "Lifetime value $2,840",
                "No abuse flags",
            ),
            _source(
                "product_quality",
                "Product quality",
                "Return rate is 11.8% versus 4.2% category baseline",
                "312 verified reviews",
                "Frequent complaint: transit denting",
                "No safety recall",
            ),
            _source(
                "economics",
                "Resolution economics",
                "Keep offer costs less than replacement",
                "Replacement landed cost $128",
                "Reverse logistics $24",
                "Refurbished recovery $82",
            ),
        ],
        options=[
            {
                "action": "partial_refund",
                "customer_value": 95,
                "company_cost": 60,
                "goal_fit": 1.0,
                "value_components": [
                    {
                        "label": "Immediate price adjustment",
                        "amount": 60,
                        "basis": "Payment adjustment offered to the customer",
                    },
                    {
                        "label": "Two-year warranty coverage",
                        "amount": 35,
                        "basis": "Expected covered-repair value from warranty history",
                    },
                ],
                "label": "$60 back + two-year warranty; customer keeps item",
            },
            {
                "action": "replacement",
                "customer_value": 249,
                "company_cost": 152,
                "goal_fit": 0.7,
                "label": "Replace and recover damaged unit",
            },
            {
                "action": "refund",
                "customer_value": 249,
                "company_cost": 191,
                "goal_fit": 0.6,
                "label": "Return for full refund",
            },
        ],
        reason="Offer $60 back plus a two-year warranty because the defect is verified as cosmetic and this preserves more customer value per company dollar than a return.",
        lesson="For verified cosmetic damage on a functional high-return product, present a voluntary keep-item discount before replacement when the customer benefit is higher and company cost is lower.",
        account_type="premium",
        auto_cost_cap=250,
        events=[
            {
                "event_type": "delivery_completed",
                "event_at": "2026-08-15T16:42:00Z",
                "data": {"order_id": "ORD-18421"},
            }
        ],
    ),
    _case(
        case_id="CASE-201-26",
        customer_id="C-201",
        customer="Aisha Patel",
        title="Package marked delivered but not found",
        task_type="delivery_not_found",
        request="The carrier says delivered, but there is no package at my door or mailroom.",
        amount=72,
        expected_mode="VERIFY",
        permission_floor="VERIFY",
        priority="HIGH",
        queue_status="CARRIER_REVIEW",
        customer_goal="Receive the missing item quickly.",
        business_guardrail="Confirm delivery evidence and open a recoverable carrier claim before reshipment.",
        sources=[
            _source(
                "order",
                "Order record",
                "Paid and fulfilled normally",
                "ORD-20188",
                "Noise-cancelling earbuds",
                "$72",
            ),
            _source(
                "carrier",
                "Carrier scans",
                "Delivered scan is 310 meters from the address",
                "No signature",
                "No delivery photo",
                "GPS confidence low",
                status="warning",
            ),
            _source(
                "address",
                "Address checks",
                "Address is unchanged across six successful deliveries",
                "Mailroom log has no matching parcel",
            ),
            _source(
                "customer_history",
                "Customer history",
                "Six orders; zero prior non-delivery claims",
                "Account age 31 months",
                "Claim rate 0%",
            ),
            _source(
                "inventory",
                "Inventory",
                "Replacement available in the nearest fulfillment center",
                "One-day dispatch",
            ),
        ],
        options=[
            {
                "action": "reship",
                "customer_value": 72,
                "company_cost": 41,
                "label": "Reship now and file carrier claim",
            },
            {
                "action": "refund",
                "customer_value": 72,
                "company_cost": 72,
                "label": "Refund after carrier trace",
            },
        ],
        reason="Reship after an analyst confirms the off-location scan and creates the carrier recovery claim.",
        lesson="A low-claim customer plus an off-location scan and absent delivery photo supports fast reshipment, but carrier recovery must be opened first.",
    ),
    _case(
        case_id="CASE-202-26",
        customer_id="C-202",
        customer="Liam Wilson",
        title="Blender motor failed after two days",
        task_type="early_product_failure",
        request="The blender worked twice and stopped on day two. The display shows motor error E17.",
        amount=89,
        expected_mode="AUTO",
        permission_floor="AUTO",
        priority="HIGH",
        queue_status="REPLACEMENT_READY",
        customer_goal="Get a working product without repeating basic troubleshooting.",
        business_guardrail="Replace only after telemetry confirms a covered hardware fault and suppress shipment from the affected batch.",
        sources=[
            _source(
                "order",
                "Order record",
                "Delivered two days ago",
                "ORD-20207",
                "BlendMax B4",
                "Warranty 365 days",
            ),
            _source(
                "diagnostics",
                "Device diagnostics",
                "E17 motor controller failure reproduced",
                "Firmware current",
                "Thermal reset failed",
                "Device serial registered to order",
            ),
            _source(
                "warranty",
                "Warranty",
                "Eligible with 363 days remaining",
                "No accidental-damage exclusion",
            ),
            _source(
                "product_quality",
                "Batch quality",
                "Batch B4-26A defect rate 8.6% versus 1.3% baseline",
                "Motor controller is the dominant failure",
                "Quality hold recommended",
            ),
            _source(
                "customer_history",
                "Customer history",
                "Nine orders, zero product-failure claims",
                "Lifetime value $1,120",
            ),
            _source(
                "inventory",
                "Inventory",
                "Replacement available from unaffected batch B4-26C",
                "Landed cost $48",
            ),
        ],
        options=[
            {
                "action": "replacement",
                "customer_value": 89,
                "company_cost": 48,
                "label": "Ship unaffected replacement and flag batch",
            },
            {
                "action": "warranty_repair",
                "customer_value": 62,
                "company_cost": 35,
                "label": "Repair in 7–10 days",
            },
        ],
        reason="Replace from an unaffected batch because telemetry proves an in-warranty hardware fault and repeat troubleshooting would lower satisfaction without reducing loss.",
        lesson="Confirmed early-life hardware failures should bypass scripted troubleshooting and route the defective batch to quality review.",
        account_type="premium",
        auto_cost_cap=250,
    ),
    _case(
        case_id="CASE-203-26",
        customer_id="C-203",
        customer="Olivia Martin",
        title="Large television cracked during freight delivery",
        task_type="freight_damage_high_value",
        request="The television screen was cracked when the installers opened the box.",
        amount=799,
        expected_mode="HUMAN",
        permission_floor="HUMAN",
        priority="URGENT",
        queue_status="HIGH_VALUE_REVIEW",
        customer_goal="Receive an undamaged television with installation rescheduled.",
        business_guardrail="Require freight evidence and supervisor approval for high-value replacement and disposal.",
        sources=[
            _source(
                "order",
                "Order record",
                "White-glove delivery completed today",
                "ORD-20352",
                "55-inch OLED",
                "$799",
            ),
            _source(
                "installer",
                "Installer report",
                "Crack documented before installation",
                "Customer signature notes damage",
                "Packaging retained",
            ),
            _source(
                "carrier",
                "Freight telemetry",
                "Impact sensor exceeded threshold in the final depot",
                "Pallet corner crushed",
            ),
            _source(
                "product_quality",
                "Product quality",
                "Model defect rate normal",
                "Damage pattern is transit-related",
            ),
            _source(
                "economics",
                "Resolution economics",
                "Replacement exposure exceeds delegated limit",
                "Carrier recovery expected $390",
                "Disposal approval required",
            ),
        ],
        options=[
            {
                "action": "replacement",
                "customer_value": 799,
                "company_cost": 486,
                "label": "Replace, reinstall, and recover from carrier",
                "value_components": [
                    {
                        "label": "Undamaged television",
                        "amount": 749,
                        "basis": "Order-line replacement value",
                    },
                    {
                        "label": "Rescheduled installation",
                        "amount": 50,
                        "basis": "White-glove service recovery schedule",
                    },
                ],
            },
            {
                "action": "warranty_repair",
                "customer_value": 650,
                "company_cost": 320,
                "goal_fit": 0.72,
                "label": "Replace the panel in home after parts inspection",
                "value_components": [
                    {
                        "label": "Restored television value",
                        "amount": 600,
                        "basis": "Authorized panel-repair valuation",
                    },
                    {
                        "label": "In-home service",
                        "amount": 50,
                        "basis": "Field-service rate card",
                    },
                ],
            },
        ],
        reason="Approve a coordinated replacement only after a supervisor assigns carrier recovery and safe disposal for the damaged high-value unit.",
        lesson="Freight evidence can prove customer eligibility, but high-value replacement and disposal remain human-controlled.",
        account_type="premium",
        auto_cost_cap=250,
    ),
    _case(
        case_id="CASE-204-26",
        customer_id="C-204",
        customer="Ethan Walker",
        title="Correct product, wrong color variant",
        task_type="wrong_variant_exchange",
        request="I ordered navy but received the black version. The barcode on the box is black.",
        amount=64,
        expected_mode="AUTO",
        permission_floor="AUTO",
        priority="NORMAL",
        queue_status="EXCHANGE_READY",
        customer_goal="Receive the ordered color without paying return shipping.",
        business_guardrail="Verify order-line and shipped barcode mismatch before issuing a prepaid exchange.",
        sources=[
            _source("order", "Order line", "Variant ordered: navy", "ORD-20411", "SKU-BAG-NVY"),
            _source(
                "warehouse",
                "Pick record",
                "Packed barcode maps to black variant",
                "SKU-BAG-BLK",
                "Station camera confirms label",
            ),
            _source(
                "customer_photo",
                "Customer photo",
                "Box barcode matches the warehouse pick",
                "Image metadata current",
            ),
            _source("inventory", "Inventory", "Navy replacement in stock", "Return label cost $12"),
        ],
        options=[
            {
                "action": "exchange",
                "customer_value": 64,
                "company_cost": 12,
                "label": "Prepaid exchange for navy variant",
            },
            {
                "action": "partial_refund",
                "amount": 18,
                "customer_value": 30,
                "company_cost": 18,
                "goal_fit": 0.42,
                "label": "Keep black variant with an $18 adjustment",
                "reason": "Offer only if the customer changes the goal from receiving navy to keeping black.",
                "lesson": "A keep-item adjustment cannot replace the customer's stated variant preference.",
            },
        ],
        reason="Create a prepaid exchange because the order-line and packed barcode prove a warehouse variant error.",
        lesson="A barcode mismatch between ordered and packed variants is sufficient evidence for a low-cost automatic exchange.",
    ),
    _case(
        case_id="CASE-205-26",
        customer_id="C-205",
        customer="Sophia Nguyen",
        title="Laptop box arrived without its charger",
        task_type="missing_component",
        request="The laptop is here, but the USB-C charger was missing from the sealed box.",
        amount=1299,
        expected_mode="AUTO",
        permission_floor="AUTO",
        priority="HIGH",
        queue_status="PART_SHIPMENT_READY",
        customer_goal="Receive the charger immediately without returning the laptop.",
        business_guardrail="Ship only the missing component after package-weight and bill-of-material evidence agree.",
        sources=[
            _source(
                "order",
                "Order record",
                "Laptop bundle includes 65W charger",
                "ORD-20573",
                "Serial linked to customer",
            ),
            _source(
                "warehouse",
                "Pack station",
                "Outbound weight is 310g below expected",
                "Tamper seal image intact",
                "Charger scan absent",
            ),
            _source(
                "product_bom",
                "Bill of materials",
                "Expected charger SKU CHG-65W",
                "Replacement value $49",
            ),
            _source(
                "customer_history",
                "Customer history",
                "Twelve orders and no missing-component claims",
                "Claim rate 0%",
            ),
            _source(
                "inventory",
                "Parts inventory",
                "Charger available for same-day shipment",
                "Landed cost $29",
            ),
        ],
        options=[
            {
                "action": "ship_missing_part",
                "customer_value": 49,
                "company_cost": 29,
                "label": "Ship charger only",
            },
            {
                "action": "replacement",
                "customer_value": 1299,
                "company_cost": 910,
                "label": "Replace entire laptop bundle",
            },
        ],
        reason="Ship the missing charger only; package-weight and scan evidence prove the omission, and replacing the whole laptop would create unnecessary loss and inconvenience.",
        lesson="Use bill-of-material and package-weight evidence to replace only a missing component when the primary product is correct.",
        account_type="premium",
        auto_cost_cap=250,
    ),
    _case(
        case_id="CASE-206-26",
        customer_id="C-206",
        customer="Marcus Reed",
        title="Four-day delay caused a missed birthday",
        task_type="late_delivery_recovery",
        request="The gift arrived four days late and missed the birthday. I still want to keep it.",
        amount=118,
        expected_mode="AUTO",
        permission_floor="AUTO",
        priority="NORMAL",
        queue_status="SERVICE_RECOVERY",
        customer_goal="Be recognized for the missed occasion while keeping the item.",
        business_guardrail="Compensate documented service failure without refunding merchandise the customer keeps.",
        sources=[
            _source(
                "order",
                "Delivery promise",
                "Promised August 10; delivered August 14",
                "ORD-20619",
                "Gift flag present",
            ),
            _source(
                "carrier",
                "Carrier events",
                "Weather exception accounts for one day; depot miss accounts for three",
                "No customer-caused delay",
            ),
            _source(
                "customer_history",
                "Customer history",
                "Five on-time prior orders",
                "No delivery credits in 24 months",
            ),
            _source(
                "economics",
                "Recovery policy",
                "Four-day service miss maps to $25 store credit",
                "Expected redemption cost $17",
            ),
        ],
        options=[
            {
                "action": "store_credit",
                "customer_value": 25,
                "company_cost": 17,
                "label": "$25 apology credit; customer keeps item",
            },
            {
                "action": "partial_refund",
                "amount": 18,
                "customer_value": 18,
                "company_cost": 18,
                "goal_fit": 0.68,
                "label": "$18 payment-method refund; customer keeps item",
                "reason": "Use only when the customer cannot use account credit.",
                "lesson": "Prefer the remedy that recognizes the service failure without refunding kept merchandise.",
            },
        ],
        reason="Issue a $25 store credit for the documented service failure while preserving the completed sale.",
        lesson="When the customer keeps a correct item, service recovery should address the delivery failure rather than refund merchandise value.",
    ),
    _case(
        case_id="CASE-207-26",
        customer_id="C-207",
        customer="Priya Shah",
        title="Food processor emitted smoke on first use",
        task_type="product_safety_incident",
        request="The food processor smoked and tripped the breaker the first time I used it.",
        amount=159,
        expected_mode="HUMAN",
        permission_floor="HUMAN",
        priority="URGENT",
        queue_status="SAFETY_ESCALATION",
        customer_goal="Get a safe resolution and clear instructions immediately.",
        business_guardrail="Never offer keep-item discounts for a possible safety defect; isolate the batch and involve the safety team.",
        sources=[
            _source(
                "order",
                "Order record",
                "Delivered today; serial verified",
                "ORD-20766",
                "Processor X2",
            ),
            _source(
                "customer_media",
                "Incident evidence",
                "Video shows smoke from motor housing",
                "Breaker trip reported",
                "Customer instructed to unplug",
            ),
            _source(
                "product_quality",
                "Safety signals",
                "Three similar incidents from batch X2-44 in 48 hours",
                "Recall not yet issued",
                "Threshold for safety investigation exceeded",
                status="warning",
            ),
            _source(
                "customer_history",
                "Customer history",
                "Seven orders, no prior safety or defect claims",
            ),
        ],
        options=[
            {
                "action": "safety_escalation",
                "customer_value": 159,
                "company_cost": 159,
                "label": "Immediate refund, no-use notice, pickup, and batch escalation",
            }
        ],
        reason="Escalate to product safety, issue no-use instructions, arrange pickup, and prepare a full refund; a human safety owner must confirm the batch action.",
        lesson="Potential electrical or thermal hazards override retention economics and must never receive a keep-item offer.",
        safety_critical=True,
    ),
    _case(
        case_id="CASE-208-26",
        customer_id="C-208",
        customer="Gabriel Lopez",
        title="Second porch-theft claim has conflicting delivery proof",
        task_type="delivery_theft_review",
        request="The package photo is not my porch, and this is the second missing delivery this month.",
        amount=130,
        expected_mode="HUMAN",
        permission_floor="HUMAN",
        priority="HIGH",
        queue_status="CLAIM_REVIEW",
        customer_goal="Receive the order or a fair replacement.",
        business_guardrail="Do not infer dishonesty from claim frequency; reconcile conflicting geo, photo, and address evidence with a human.",
        sources=[
            _source(
                "carrier",
                "Delivery proof",
                "Photo does not match saved address facade",
                "GPS is 42 meters away",
                "No signature",
                status="warning",
            ),
            _source(
                "customer_history",
                "Claim history",
                "Two non-delivery claims across 21 orders",
                "Previous claim had carrier-confirmed misdelivery",
                "No chargebacks",
            ),
            _source(
                "address",
                "Address intelligence",
                "Multi-unit entrance has repeated carrier exceptions",
                "Safe-drop preference disabled",
            ),
            _source(
                "inventory", "Inventory", "Replacement available", "Carrier recovery uncertain"
            ),
        ],
        options=[
            {
                "action": "reship",
                "customer_value": 130,
                "company_cost": 78,
                "label": "Reship to pickup location",
            },
            {
                "action": "refund",
                "customer_value": 130,
                "company_cost": 130,
                "label": "Refund after carrier investigation",
            },
        ],
        reason="A human should validate the mismatched proof and, if confirmed, reship to a secure pickup location rather than blaming the customer or repeating doorstep delivery.",
        lesson="Claim frequency is a review signal, not proof of abuse; use delivery evidence and choose a safer fulfillment method.",
    ),
    _case(
        case_id="CASE-209-26",
        customer_id="C-209",
        customer="Natalie Kim",
        title="Worn shoes are uncomfortable after one week",
        task_type="fit_dissatisfaction",
        request="I wore the shoes outside twice, but they hurt. Can I return them for something else?",
        amount=110,
        expected_mode="VERIFY",
        permission_floor="VERIFY",
        priority="NORMAL",
        queue_status="FLEX_RETURN_REVIEW",
        customer_goal="Move to a better-fitting product without losing the purchase value.",
        business_guardrail="Apply the worn-item exception only when loyalty and recoverable resale value justify it.",
        sources=[
            _source(
                "order",
                "Order record",
                "Delivered seven days ago",
                "Size selected from prior purchase",
                "$110",
            ),
            _source(
                "customer_history",
                "Customer history",
                "27 orders over six years",
                "Lifetime value $4,920",
                "Two returns; no policy abuse",
            ),
            _source(
                "product_quality",
                "Fit reviews",
                "22% of reviews report narrow fit",
                "Return rate 14.1% versus 8.0% category baseline",
                "Rating 3.8/5",
            ),
            _source(
                "recovery",
                "Resale recovery",
                "Light wear qualifies for outlet channel",
                "Expected recovery $72",
                "Cleaning cost $9",
            ),
        ],
        options=[
            {
                "action": "store_credit",
                "customer_value": 110,
                "company_cost": 38,
                "label": "Full store credit after inspected return",
            },
            {
                "action": "deny",
                "customer_value": 0,
                "company_cost": 0,
                "label": "Apply standard worn-item exclusion",
            },
        ],
        reason="Offer full store credit after inspection because loyalty and outlet recovery keep the expected company loss to $38 while preserving the customer relationship.",
        lesson="Worn-item exceptions should use customer history, product fit signals, and recovery value rather than a blanket return rule.",
    ),
    _case(
        case_id="CASE-210-26",
        customer_id="C-210",
        customer="Jordan Ellis",
        title="Returned phone serial does not match the order",
        task_type="serial_mismatch_return",
        request="This phone is defective. I want the $699 refund today.",
        amount=699,
        expected_mode="DENY",
        permission_floor="DENY",
        priority="URGENT",
        queue_status="IDENTITY_MISMATCH",
        customer_goal="Receive a refund for the device presented.",
        business_guardrail="Never refund a high-value serialized item that cannot be linked to the order; provide an appeal path.",
        sources=[
            _source(
                "order", "Order serial", "Order is linked to serial PH-77-A91", "ORD-21031", "$699"
            ),
            _source(
                "return_scan",
                "Return scan",
                "Presented device serial is PH-12-Q44",
                "Serial and IMEI both mismatch",
            ),
            _source(
                "activation",
                "Activation history",
                "Presented device activated to a different account before this order",
                "Order device remains active",
            ),
            _source(
                "customer_history",
                "Customer history",
                "Four orders and no prior return issues",
                "Mismatch still requires resolution before payment",
            ),
        ],
        options=[
            {
                "action": "deny",
                "customer_value": 0,
                "company_cost": 0,
                "label": "Deny current refund and open serial-evidence appeal",
            }
        ],
        reason="Deny the refund for the presented device because two independent identifiers do not match the order; invite the customer to submit the correct unit or appeal the evidence.",
        lesson="Customer history cannot override serialized-asset identity, but denial must include a clear correction and appeal path.",
    ),
    _case(
        case_id="CASE-211-26",
        customer_id="C-211",
        customer="Hannah Moore",
        title="Sealed parcel arrived with no product inside",
        task_type="empty_box_claim",
        request="The box was sealed, but the camera was missing when I opened it.",
        amount=140,
        expected_mode="AUTO",
        permission_floor="AUTO",
        priority="HIGH",
        queue_status="REPLACEMENT_READY",
        customer_goal="Receive the missing camera quickly.",
        business_guardrail="Require weight-chain or pack-station evidence before replacing an allegedly empty parcel.",
        sources=[
            _source(
                "warehouse",
                "Pack station",
                "Expected packed weight 1.24kg; recorded 0.39kg",
                "Product scan occurred but weight gate failed open",
            ),
            _source(
                "carrier",
                "Carrier weight chain",
                "Weight remained 0.39kg through delivery",
                "No tamper exception",
            ),
            _source(
                "customer_media",
                "Unboxing evidence",
                "Time-stamped video shows intact seal and empty insert",
                "Metadata matches delivery window",
            ),
            _source(
                "customer_history",
                "Customer history",
                "Eleven orders; no empty-box claims",
                "No abuse signals",
            ),
        ],
        options=[
            {
                "action": "replacement",
                "customer_value": 140,
                "company_cost": 82,
                "label": "Replace and create warehouse shrink investigation",
            },
            {
                "action": "refund",
                "customer_value": 140,
                "company_cost": 140,
                "goal_fit": 0.82,
                "label": "Refund after preserving fulfillment-loss evidence",
                "reason": "Use when replacement inventory cannot meet the customer's delivery need.",
                "lesson": "Replacement is preferred while stock is available because it restores the intended outcome at lower cost.",
            },
        ],
        reason="Replace the camera because the entire weight chain proves the parcel left fulfillment without the product.",
        lesson="Weight-chain evidence can distinguish fulfillment loss from unsupported empty-box claims and enable rapid replacement.",
    ),
    _case(
        case_id="CASE-044-26",
        customer_id="C-044",
        customer="Maya Carter",
        title="Marketplace handbag may be counterfeit",
        task_type="counterfeit_marketplace_claim",
        request="The authentication tag fails and the stitching does not match the brand photos.",
        amount=480,
        expected_mode="HUMAN",
        permission_floor="HUMAN",
        priority="URGENT",
        queue_status="TRUST_AND_SAFETY",
        customer_goal="Receive a refund and avoid returning a questionable item to circulation.",
        business_guardrail="Coordinate refund, evidence preservation, and seller controls; never auto-resolve marketplace authenticity findings.",
        sources=[
            _source(
                "order", "Marketplace order", "Third-party seller LuxeLane-41", "ORD-04492", "$480"
            ),
            _source(
                "authentication",
                "Brand authentication",
                "Tag signature invalid",
                "Serial not recognized",
                "Photo differences exceed threshold",
            ),
            _source(
                "seller_risk",
                "Seller risk",
                "Seven authenticity complaints in 14 days",
                "Complaint rate increased 5.2×",
                "Payout hold eligible",
                status="warning",
            ),
            _source(
                "customer_history",
                "Customer history",
                "Premium customer; 16 orders; no authenticity claims",
            ),
        ],
        options=[
            {
                "action": "seller_investigation",
                "customer_value": 480,
                "company_cost": 480,
                "label": "Refund, preserve item, hold seller payout, investigate inventory",
            },
            {
                "action": "refund",
                "customer_value": 440,
                "company_cost": 480,
                "goal_fit": 0.78,
                "label": "Refund customer without coordinated seller containment",
                "reason": "Customer-only recovery leaves related inventory and seller exposure unresolved.",
                "lesson": "Authenticity evidence must contain systemic marketplace risk, not only reimburse one order.",
            },
        ],
        reason="Trust and Safety must coordinate the refund and seller action because the evidence affects other customers and marketplace inventory.",
        lesson="Counterfeit evidence is systemic: resolve the customer, preserve the item, and contain seller risk in one reviewed workflow.",
        account_type="premium",
        auto_cost_cap=250,
    ),
    _case(
        case_id="CASE-771-26",
        customer_id="C-771",
        customer="Elena Torres",
        title="Known battery defect discovered just after warranty",
        task_type="warranty_grace_exception",
        request="My headphones stopped charging two days after the warranty ended. Support says this batch has a known battery issue.",
        amount=170,
        expected_mode="HUMAN",
        permission_floor="HUMAN",
        priority="NORMAL",
        queue_status="LEARNING_REVIEW",
        customer_goal="Receive coverage for a known defect despite the two-day timing gap.",
        business_guardrail="A reviewer must teach and approve the warranty-grace exception before it can be reused.",
        sources=[
            _source(
                "order",
                "Order record",
                "Warranty expired two days ago",
                "ORD-77104",
                "Headphones H9",
            ),
            _source(
                "diagnostics",
                "Diagnostics",
                "Battery controller cannot accept charge",
                "No moisture or impact flags",
                "Serial verified",
            ),
            _source(
                "product_quality",
                "Batch quality",
                "Battery failure rate 9.2% versus 1.1% baseline",
                "Service bulletin SB-H9-17 exists",
            ),
            _source(
                "customer_history",
                "Customer history",
                "Eight orders; zero warranty claims",
                "Account age 43 months",
            ),
            _source(
                "economics",
                "Repair economics",
                "Repair cost $54 versus replacement cost $106",
                "Customer value restored $170",
            ),
        ],
        options=[
            {
                "action": "warranty_repair",
                "customer_value": 170,
                "company_cost": 54,
                "label": "Honor repair under a two-day grace exception",
            },
            {
                "action": "store_credit",
                "customer_value": 40,
                "company_cost": 29,
                "label": "Offer goodwill credit",
            },
        ],
        reason="Approve a warranty repair because a documented batch defect, clean diagnostics, and a two-day timing gap make the exception fair and lower-cost than replacement.",
        lesson="For a verified service-bulletin defect within 14 days after warranty, offer repair when diagnostics exclude customer damage and repair cost is below replacement cost.",
    ),
    _case(
        case_id="CASE-841-26",
        customer_id="C-841",
        customer="Noah Bennett",
        title="Comparable battery defect awaits correction replay",
        task_type="warranty_grace_exception",
        request="My speaker battery failed three days after warranty. The diagnostic report links it to service bulletin SB-P6-08.",
        amount=130,
        expected_mode="HUMAN",
        permission_floor="HUMAN",
        priority="NORMAL",
        queue_status="LEARNING_REPLAY",
        customer_goal="Receive repair coverage for the same known-defect grace-period pattern.",
        business_guardrail="Replay only a verified lesson that matches defect bulletin, diagnostic result, and grace window.",
        sources=[
            _source(
                "order",
                "Order record",
                "Warranty expired three days ago",
                "ORD-84117",
                "Speaker P6",
            ),
            _source(
                "diagnostics",
                "Diagnostics",
                "Battery controller failure reproduced",
                "Serial verified",
                "No impact or moisture flags",
            ),
            _source(
                "product_quality",
                "Batch quality",
                "Service bulletin SB-P6-08 covers the serial range",
                "Failure rate 7.4% versus 0.9% baseline",
            ),
            _source(
                "customer_history",
                "Customer history",
                "Five orders and no warranty claims",
                "Account age 28 months",
            ),
            _source(
                "economics",
                "Repair economics",
                "Repair cost $42 versus replacement cost $79",
                "Customer value restored $130",
            ),
        ],
        options=[
            {
                "action": "warranty_repair",
                "customer_value": 130,
                "company_cost": 42,
                "label": "Replay the verified grace-period repair rule",
            },
            {
                "action": "store_credit",
                "customer_value": 30,
                "company_cost": 21,
                "label": "Offer generic goodwill credit",
            },
        ],
        reason="Apply the verified 14-day warranty-grace lesson because the same diagnostic exclusions and a listed service-bulletin defect are present.",
        lesson="Replay warranty grace only when the failure is within 14 days, a matching service bulletin exists, and diagnostics exclude customer damage.",
    ),
    _case(
        case_id="CASE-992-26",
        customer_id="C-992",
        customer="Amir Hassan",
        title="One chair missing from a four-chair shipment",
        task_type="partial_shipment",
        request="Only three of the four dining chairs arrived. I need the missing chair, not a full return.",
        amount=380,
        expected_mode="AUTO",
        permission_floor="AUTO",
        priority="HIGH",
        queue_status="PART_SHIPMENT_READY",
        customer_goal="Receive the missing matching chair quickly.",
        business_guardrail="Reship only the missing quantity after carton and carrier scans establish partial fulfillment.",
        sources=[
            _source(
                "order",
                "Order line",
                "Quantity four at $95 each",
                "ORD-99263",
                "One coordinated set",
            ),
            _source(
                "warehouse",
                "Carton manifest",
                "Only three carton IDs were closed",
                "Fourth label created but never inducted",
            ),
            _source(
                "carrier",
                "Carrier events",
                "Three cartons delivered and photographed",
                "No fourth tracking acceptance",
            ),
            _source(
                "inventory",
                "Inventory",
                "Matching lot has six chairs available",
                "Single-chair landed cost $61",
            ),
        ],
        options=[
            {
                "action": "reship",
                "customer_value": 95,
                "company_cost": 61,
                "label": "Ship one matching chair",
            },
            {
                "action": "refund",
                "customer_value": 380,
                "company_cost": 380,
                "label": "Return and refund the full set",
            },
        ],
        reason="Ship one chair from the matching lot because warehouse and carrier evidence prove a one-unit short shipment.",
        lesson="Resolve partial shipments at the missing-unit level when quantity and tracking evidence are unambiguous.",
    ),
    _case(
        case_id="CASE-212-26",
        customer_id="C-212",
        customer="Chloe Anderson",
        title="Smart lock fails after an outdated firmware pairing",
        task_type="guided_product_recovery",
        request="The smart lock stopped responding two days after setup. I think it is defective.",
        amount=186,
        expected_mode="AUTO",
        permission_floor="AUTO",
        priority="HIGH",
        queue_status="REMOTE_FIX_READY",
        customer_goal="Restore the product now without waiting for a return.",
        business_guardrail="Use remote recovery only when telemetry identifies a reversible software state and no safety or hardware signal exists.",
        sources=[
            _source(
                "order", "Order record", "Delivered four days ago", "ORD-21245", "Smart Lock S3"
            ),
            _source(
                "diagnostics",
                "Device telemetry",
                "Hardware self-test passes",
                "Pairing token expired after firmware 3.1 rollback",
                "Battery 91%",
            ),
            _source(
                "knowledge",
                "Recovery knowledge",
                "Firmware 3.1.2 plus re-pair resolves 96% of identical cases",
                "Average assisted time 7 minutes",
            ),
            _source(
                "product_quality",
                "Product quality",
                "Hardware defect rate normal",
                "No safety signals",
            ),
        ],
        options=[
            {
                "action": "guided_troubleshooting",
                "customer_value": 186,
                "company_cost": 4,
                "label": "Push firmware and guide re-pair",
            },
            {
                "action": "replacement",
                "customer_value": 186,
                "company_cost": 109,
                "label": "Replace before diagnosing",
            },
        ],
        reason="Push the fixed firmware and guide re-pairing because telemetry proves a reversible software state, restoring value faster than replacement.",
        lesson="When device telemetry passes hardware checks and a high-success recovery exists, resolve remotely before creating reverse logistics.",
    ),
    _case(
        case_id="CASE-213-26",
        customer_id="C-213",
        customer="Daniel Brooks",
        title="Frequent-return customer reports a known zipper defect",
        task_type="repeat_claim_known_defect",
        request="The backpack zipper split after three days. I know I return a lot, but this one is genuinely broken.",
        amount=85,
        expected_mode="VERIFY",
        permission_floor="VERIFY",
        priority="NORMAL",
        queue_status="BALANCED_REVIEW",
        customer_goal="Receive a fair remedy without being dismissed because of prior returns.",
        business_guardrail="Treat return frequency as context, not guilt; corroborate the present defect and choose a bounded remedy.",
        sources=[
            _source(
                "customer_history",
                "Customer history",
                "Ten orders and eight returns in 12 months",
                "Six were fit/style returns",
                "No chargebacks or item mismatches",
                status="warning",
            ),
            _source(
                "damage_photo",
                "Defect inspection",
                "Photo shows zipper teeth separated at the factory seam",
                "Wear pattern inconsistent with overload",
                "Confidence 96.4%",
            ),
            _source(
                "product_quality",
                "Product quality",
                "Zipper defect rate 7.9% versus 1.6% baseline",
                "38 recent verified complaints",
                "Supplier corrective action open",
            ),
            _source(
                "economics",
                "Resolution economics",
                "Customer accepts local zipper repair",
                "Repair estimate $20",
                "Return/refund expected loss $67",
            ),
        ],
        options=[
            {
                "action": "partial_refund",
                "customer_value": 45,
                "company_cost": 25,
                "label": "$25 repair allowance; customer keeps backpack",
            },
            {
                "action": "replacement",
                "customer_value": 85,
                "company_cost": 58,
                "label": "Replace with revised zipper batch",
            },
        ],
        reason="Offer a $25 repair allowance if the customer wants to keep the backpack; present history raises review level but product evidence independently confirms the defect.",
        lesson="High return frequency should increase verification, not erase valid current evidence; use product defect rates and repair economics for the remedy.",
    ),
    _case(
        case_id="CASE-301-26",
        customer_id="E-301",
        customer="Billing Operations Team",
        title="Unexpected infrastructure bill after a workload migration",
        task_type="enterprise_billing_anomaly",
        request="Our monthly infrastructure estimate increased by $2,140 after a migration. Find the cause and stop avoidable spend without interrupting production.",
        amount=2_140,
        expected_mode="VERIFY",
        permission_floor="VERIFY",
        priority="HIGH",
        queue_status="COST_REVIEW_READY",
        customer_goal="Remove verified waste while preserving production availability.",
        business_guardrail="Never stop a resource until ownership, dependency, utilization, and production classification are independently confirmed.",
        sources=[
            _source(
                "billing_export",
                "Billing ledger",
                "A detached compute pool created $480 of avoidable spend",
                "Invoice INV-E301",
                "Resource group RG-LEGACY-17",
                "Charge correlation 100%",
            ),
            _source(
                "resource_inventory",
                "Resource inventory",
                "Legacy pool remains active after migration completion",
                "Owner Platform Team",
                "Environment non-production",
                "Migration ticket MIG-882 closed",
            ),
            _source(
                "dependency_graph",
                "Dependency graph",
                "No production request, queue, database, or deployment depends on the pool",
                "Zero inbound edges",
                "Zero outbound data flows",
            ),
            _source(
                "utilization",
                "Telemetry",
                "CPU below 1% and zero requests for 21 days",
                "Last workload 2026-07-25",
                "No scheduled jobs",
            ),
            _source(
                "change_record",
                "Change management",
                "Approved migration explicitly retires the legacy pool",
                "Change CHG-10482",
                "Rollback window expired successfully",
            ),
        ],
        options=[
            {
                "action": "cost_containment",
                "customer_value": 480,
                "company_cost": 12,
                "label": "Schedule shutdown, create final snapshot, and add budget anomaly controls",
            },
            {
                "action": "guided_troubleshooting",
                "customer_value": 80,
                "company_cost": 4,
                "label": "Explain cost only; leave waste running",
            },
        ],
        reason="Prepare a scheduled shutdown with a final snapshot because billing, ownership, dependency, utilization, and change evidence agree that the pool is retired and non-production.",
        lesson="Contain infrastructure waste only when billing records correlate to an owner-approved, dependency-free, idle resource and a reversible recovery point is created first.",
        account_type="enterprise",
        contract_type="business_standard",
        customer_segment="enterprise",
    ),
    _case(
        case_id="CASE-302-26",
        customer_id="E-302",
        customer="Application Platform Team",
        title="Production deployment failed health checks",
        task_type="enterprise_failed_deployment",
        request="The new release is returning errors. Restore the last healthy version and prove that the service recovered.",
        amount=950,
        expected_mode="AUTO",
        permission_floor="AUTO",
        priority="URGENT",
        queue_status="ROLLBACK_READY",
        customer_goal="Restore service quickly without introducing a second unsafe change.",
        business_guardrail="Rollback only when the failing release is isolated, the previous artifact is immutable and healthy, and database compatibility is proven.",
        sources=[
            _source(
                "deployment",
                "Deployment controller",
                "Release 7.18.0 failed three health gates",
                "Error rate 31%",
                "Started 18 minutes ago",
                "No other change in window",
            ),
            _source(
                "previous_release",
                "Artifact registry",
                "Release 7.17.4 is signed, immutable, and was healthy",
                "Digest verified",
                "14-day successful runtime",
            ),
            _source(
                "schema_compatibility",
                "Schema registry",
                "Rollback is backward compatible",
                "No destructive migration",
                "Contract tests pass",
            ),
            _source(
                "service_health",
                "Service telemetry",
                "Failures began within two minutes of the release",
                "Latency +420%",
                "Dependency health normal",
            ),
            _source(
                "runbook",
                "Change policy",
                "Automated rollback is approved inside the 30-minute window",
                "Runbook RB-DEPLOY-04",
                "Maximum one rollback attempt",
            ),
        ],
        options=[
            {
                "action": "rollback_deployment",
                "customer_value": 950,
                "company_cost": 18,
                "label": "Roll back to signed healthy release and verify recovery",
            },
            {
                "action": "guided_troubleshooting",
                "customer_value": 240,
                "company_cost": 45,
                "label": "Keep failing release while an engineer diagnoses",
            },
        ],
        reason="Roll back to release 7.17.4 because timing, health, artifact, schema, and runbook evidence isolate the new release and prove a safe recovery path.",
        lesson="A deployment may roll back automatically only inside a tested window with an immutable healthy artifact and proven schema compatibility.",
        account_type="premium",
        contract_type="business_standard",
        customer_segment="enterprise",
        auto_cost_cap=100,
    ),
    _case(
        case_id="CASE-303-26",
        customer_id="E-303",
        customer="Identity Administration Team",
        title="Service account denied access after policy cleanup",
        task_type="enterprise_access_denied",
        request="A reporting job can no longer read its approved dataset. Restore only the access it actually needs.",
        amount=420,
        expected_mode="VERIFY",
        permission_floor="VERIFY",
        priority="HIGH",
        queue_status="ACCESS_FIX_READY",
        customer_goal="Restore the reporting job without broadening access.",
        business_guardrail="Generate the smallest policy delta, prohibit wildcard privileges, and require identity-owner confirmation before applying it.",
        sources=[
            _source(
                "authorization_trace",
                "Authorization evaluator",
                "One explicit read permission was removed",
                "Principal svc-reporting",
                "Dataset finance_daily",
                "Denied action read.object",
            ),
            _source(
                "audit_log",
                "Audit log",
                "Job previously read only the approved dataset",
                "90-day scope",
                "No write operations",
                "No cross-project access",
            ),
            _source(
                "identity_owner",
                "Identity registry",
                "Principal owner and workload binding are current",
                "Owner Data Operations",
                "Workload signature verified",
            ),
            _source(
                "data_classification",
                "Data catalog",
                "Dataset permits this reporting purpose",
                "Classification internal-confidential",
                "Purpose binding FIN-REPORT-2",
            ),
            _source(
                "policy_diff",
                "Policy simulator",
                "Single-resource read grant passes; wildcard alternatives rejected",
                "No privilege escalation",
                "Simulation 42/42 allowed paths",
            ),
        ],
        options=[
            {
                "action": "least_privilege_fix",
                "customer_value": 420,
                "company_cost": 9,
                "label": "Apply one-resource read grant after owner confirmation",
            },
            {
                "action": "deny",
                "customer_value": 0,
                "company_cost": 0,
                "label": "Leave reporting unavailable",
            },
        ],
        reason="Apply the simulated one-resource read grant after identity-owner confirmation; the trace proves the missing permission and rejects broader access.",
        lesson="Access recovery must be derived from the denied action, historical use, identity ownership, data purpose, and a wildcard-free policy simulation.",
        account_type="enterprise",
        contract_type="business_standard",
        customer_segment="enterprise",
    ),
    _case(
        case_id="CASE-304-26",
        customer_id="E-304",
        customer="Data Services Team",
        title="Database latency caused by exhausted read capacity",
        task_type="enterprise_database_latency",
        request="Checkout reads are timing out. Recover capacity without making a destructive schema change.",
        amount=780,
        expected_mode="AUTO",
        permission_floor="AUTO",
        priority="URGENT",
        queue_status="CAPACITY_RECOVERY_READY",
        customer_goal="Restore database performance while preserving consistency and rollback safety.",
        business_guardrail="Use a reversible capacity action only after excluding locks, bad queries, storage faults, and provider incidents.",
        sources=[
            _source(
                "database_metrics",
                "Database telemetry",
                "Read capacity is saturated at 98%",
                "Write capacity 41%",
                "p99 read latency 2.8 seconds",
            ),
            _source(
                "query_analysis",
                "Query analyzer",
                "Query shapes and plans are unchanged",
                "No new full scans",
                "Top query mix stable",
            ),
            _source(
                "lock_analysis",
                "Transaction diagnostics",
                "No blocking lock chain or deadlock surge",
                "Maximum lock wait 11 ms",
                "Conflict rate baseline",
            ),
            _source(
                "change_history",
                "Change history",
                "No schema or configuration change in the incident window",
                "Last change 9 days ago",
            ),
            _source(
                "capacity_plan",
                "Capacity controller",
                "One read replica restores 45% headroom and is reversible",
                "Quota available",
                "Estimated cost $64",
                "Automatic expiry in 24 hours",
            ),
        ],
        options=[
            {
                "action": "database_capacity_recovery",
                "customer_value": 780,
                "company_cost": 64,
                "label": "Add temporary read capacity, rebalance, verify latency, and expire after 24 hours",
            },
            {
                "action": "guided_troubleshooting",
                "customer_value": 160,
                "company_cost": 20,
                "label": "Continue diagnosis while timeouts persist",
            },
        ],
        reason="Add one temporary read replica because independent telemetry excludes locks and change regressions while the capacity plan proves a reversible bounded recovery.",
        lesson="Capacity recovery can be automatic only when saturation is isolated, alternate causes are excluded, quota exists, cost is capped, and capacity expires automatically.",
        account_type="premium",
        contract_type="business_standard",
        customer_segment="enterprise",
        auto_cost_cap=100,
    ),
    _case(
        case_id="CASE-305-26",
        customer_id="E-305",
        customer="API Reliability Team",
        title="Retry storm is amplifying API throttling",
        task_type="enterprise_api_throttling",
        request="Clients are receiving throttling errors and retrying too aggressively. Stabilize traffic without losing accepted requests.",
        amount=360,
        expected_mode="AUTO",
        permission_floor="AUTO",
        priority="HIGH",
        queue_status="TRAFFIC_FIX_READY",
        customer_goal="Restore stable API throughput without dropping accepted work.",
        business_guardrail="Change only retry and queue controls proven safe by load simulation; do not increase quota until the storm is contained.",
        sources=[
            _source(
                "request_metrics",
                "API telemetry",
                "Base traffic rose 8% while retries rose 640%",
                "Throttle rate 22%",
                "Accepted request IDs preserved",
            ),
            _source(
                "client_trace",
                "Distributed trace",
                "Three clients retry immediately without jitter",
                "Median retry interval 40 ms",
                "Same idempotency keys reused",
            ),
            _source(
                "capacity",
                "Capacity service",
                "Backend has healthy capacity at normal request rate",
                "CPU 54% without retries",
                "No dependency saturation",
            ),
            _source(
                "load_simulation",
                "Traffic simulator",
                "Exponential backoff plus jitter restores 99.4% completion",
                "No accepted request loss",
                "Queue depth bounded",
            ),
            _source(
                "runbook",
                "Reliability runbook",
                "Retry-policy mitigation is pre-authorized",
                "Runbook RB-API-07",
                "Automatic rollback on error increase",
            ),
        ],
        options=[
            {
                "action": "traffic_stabilization",
                "customer_value": 360,
                "company_cost": 8,
                "label": "Apply bounded backoff, jitter, and queue protection; verify completion rate",
            },
            {
                "action": "quota_adjustment",
                "customer_value": 120,
                "company_cost": 95,
                "label": "Increase quota without stopping retry amplification",
            },
        ],
        reason="Apply the simulated retry controls because traces prove retry amplification, normal traffic fits capacity, and load testing proves the bounded mitigation.",
        lesson="Contain retry amplification before changing quota; require preserved idempotency, successful load simulation, and automatic rollback thresholds.",
        account_type="premium",
        contract_type="business_standard",
        customer_segment="enterprise",
        auto_cost_cap=50,
    ),
    _case(
        case_id="CASE-306-26",
        customer_id="E-306",
        customer="Security Operations Team",
        title="Credential used from an impossible travel location",
        task_type="enterprise_credential_compromise",
        request="A privileged credential appears to be compromised. Contain access and preserve evidence immediately.",
        amount=5_000,
        expected_mode="HUMAN",
        permission_floor="HUMAN",
        priority="URGENT",
        queue_status="SECURITY_OWNER_REQUIRED",
        customer_goal="Stop unauthorized access without destroying forensic evidence.",
        business_guardrail="A security owner must approve privileged-session revocation; preserve evidence before rotation and prohibit automated resource deletion.",
        sources=[
            _source(
                "identity_events",
                "Identity telemetry",
                "Same credential used from locations 8,100 km apart within 14 minutes",
                "MFA absent on second session",
                "Risk engine critical",
            ),
            _source(
                "audit_log",
                "Security audit log",
                "Second session enumerated secrets and policies",
                "No destructive action observed",
                "Session ID SEC-8821",
            ),
            _source(
                "asset_scope",
                "Asset inventory",
                "Credential can administer three production services",
                "Owner Security Operations",
                "Break-glass replacement available",
            ),
            _source(
                "forensic_snapshot",
                "Forensic service",
                "Audit and session evidence preserved immutably",
                "Chain of custody COC-306",
                "Hash verified",
            ),
            _source(
                "response_plan",
                "Incident response",
                "Scoped revoke, rotate, isolate, and notify plan validated",
                "Plan IR-12",
                "Human incident commander required",
            ),
        ],
        options=[
            {
                "action": "security_containment",
                "customer_value": 5_000,
                "company_cost": 85,
                "label": "Approve scoped revoke, rotation, isolation, and incident creation",
            },
        ],
        reason="Execute the scoped credential containment plan only after the incident commander confirms identity and business continuity; forensic evidence is already preserved.",
        lesson="Privileged credential compromise remains human-owned even with exact telemetry; the agent should preserve evidence and prebuild the bounded containment workflow.",
        account_type="enterprise",
        contract_type="custom_sla",
        customer_segment="enterprise",
        auto_cost_cap=100,
    ),
    _case(
        case_id="CASE-307-26",
        customer_id="E-307",
        customer="Business Continuity Team",
        title="Restore request after accidental dataset deletion",
        task_type="enterprise_backup_restore",
        request="A dataset was deleted accidentally. Restore the latest valid recovery point without overwriting current production data.",
        amount=3_500,
        expected_mode="HUMAN",
        permission_floor="HUMAN",
        priority="URGENT",
        queue_status="RESTORE_APPROVAL_REQUIRED",
        customer_goal="Recover the deleted dataset with proven integrity and no production overwrite.",
        business_guardrail="Restore into isolation, verify consistency and ownership, and require the data owner to approve promotion.",
        sources=[
            _source(
                "deletion_audit",
                "Audit log",
                "Dataset deleted by approved operator command at 17:42 UTC",
                "Dataset orders_archive",
                "No evidence of malicious access",
            ),
            _source(
                "backup_catalog",
                "Backup catalog",
                "Recovery point 17:30 UTC is complete and immutable",
                "Backup BK-307-1730",
                "Checksum verified",
            ),
            _source(
                "dependency_graph",
                "Data lineage",
                "Four downstream reports depend on the dataset",
                "No transactional writer depends on restore target",
            ),
            _source(
                "restore_simulation",
                "Recovery verifier",
                "Isolated restore passes row-count, schema, and referential checks",
                "0.02% expected recovery gap",
                "No overwrite required",
            ),
            _source(
                "ownership",
                "Data ownership",
                "Business data owner identified and available",
                "Owner Business Continuity",
                "Promotion requires approval",
            ),
        ],
        options=[
            {
                "action": "isolated_restore",
                "customer_value": 3_500,
                "company_cost": 140,
                "label": "Restore into isolation, validate, then request promotion approval",
            },
        ],
        reason="Create the isolated restore from backup BK-307-1730 because audit, backup, lineage, simulation, and ownership evidence agree; promotion remains human-approved.",
        lesson="Never restore directly over production; validate an immutable recovery point in isolation and require the accountable data owner to approve promotion.",
        account_type="enterprise",
        contract_type="custom_sla",
        customer_segment="enterprise",
        auto_cost_cap=150,
    ),
    _case(
        case_id="CASE-308-26",
        customer_id="E-308",
        customer="Capacity Planning Team",
        title="Regional quota blocks an approved launch",
        task_type="enterprise_quota_request",
        request="An approved launch needs a temporary regional quota increase. Validate capacity, cost, and abuse risk before requesting it.",
        amount=1_200,
        expected_mode="VERIFY",
        permission_floor="VERIFY",
        priority="HIGH",
        queue_status="QUOTA_APPROVAL_READY",
        customer_goal="Obtain enough temporary capacity for the approved launch.",
        business_guardrail="Grant only the calculated temporary increment, attach expiry, verify budget, and prohibit unexplained step-function increases.",
        sources=[
            _source(
                "launch_plan",
                "Change management",
                "Launch is approved for 72 hours",
                "Change CHG-308",
                "Expected peak 740 units",
            ),
            _source(
                "usage_history",
                "Capacity telemetry",
                "Current sustained use 480 units with predictable launch profile",
                "No unexplained spikes",
                "Forecast confidence 96%",
            ),
            _source(
                "quota_model",
                "Quota calculator",
                "Temporary increase from 600 to 820 covers peak plus 10% headroom",
                "Automatic expiry 96 hours",
                "No permanent increase",
            ),
            _source(
                "budget",
                "Budget control",
                "Maximum projected incremental cost is $35",
                "Budget owner confirmed",
                "Alert at 80%",
            ),
            _source(
                "risk",
                "Abuse prevention",
                "Account, workload, and payment posture verified",
                "No abuse signal",
                "Region capacity available",
            ),
        ],
        options=[
            {
                "action": "quota_adjustment",
                "customer_value": 1_200,
                "company_cost": 35,
                "label": "Approve bounded temporary quota with expiry and budget alerts",
            },
            {
                "action": "deny",
                "customer_value": 0,
                "company_cost": 0,
                "label": "Block the approved launch",
            },
        ],
        reason="Request a temporary quota of 820 after approval because launch, usage, capacity, budget, and abuse-prevention evidence agree on the bounded need.",
        lesson="Quota increases should be calculated from observed demand, cost-capped, risk-checked, and automatically expire after the approved launch window.",
        account_type="enterprise",
        contract_type="business_standard",
        customer_segment="enterprise",
    ),
)


def analyst_case_records() -> list[dict[str, Any]]:
    return deepcopy(list(ANALYST_CASES))


def analyst_case_record(case_id: str) -> dict[str, Any] | None:
    return next((record for record in analyst_case_records() if record["case_id"] == case_id), None)


def customer_context(customer_id: str) -> dict[str, Any]:
    record = next(
        (item for item in ANALYST_CASES if item["customer"]["customer_id"] == customer_id),
        None,
    )
    if record is None:
        return {
            "customer": {
                "customer_id": customer_id,
                "display_name": "Unassigned customer",
                "account_type": "standard",
                "region": "US",
                "contract_type": "retail_standard",
            },
            "events": [],
            "payments": [],
            "case_evidence": {},
        }
    return {
        "customer": deepcopy(record["customer"]),
        "events": deepcopy(record["events"]),
        "payments": deepcopy(record["payments"]),
        "case_evidence": {
            "issue_type": record["task_type"],
            "customer_segment": record["customer_segment"],
            "evidence_as_of": record["evidence_as_of"],
            "customer_goal": record["customer_goal"],
            "business_guardrail": record["business_guardrail"],
            "evidence_required": deepcopy(record["evidence_required"]),
            "evidence_sources": deepcopy(record["evidence_sources"]),
            "resolution_options": deepcopy(record["resolution_options"]),
            "resolution_constraints": deepcopy(record["resolution_constraints"]),
        },
    }
