from __future__ import annotations

from .domain import AgentProposal, CustomerCase, ResolutionEvidence, WorkflowPlan, WorkflowStepPlan


def build_workflow_plan(
    case: CustomerCase,
    proposal: AgentProposal,
    evidence: ResolutionEvidence | None,
) -> WorkflowPlan:
    """Compile a proposal into an explicit, reviewable business workflow."""

    action = proposal.action_type
    customer_goal = evidence.customer_goal if evidence else case.request_text
    templates = _WORKFLOW_TEMPLATES.get(action, _WORKFLOW_TEMPLATES["deny"])
    steps = tuple(
        WorkflowStepPlan(
            step_id=f"{index:02d}-{operation.replace('_', '-')}",
            title=title,
            system=system,
            operation=operation,
            detail=_render_detail(detail, case, proposal),
            reversible=reversible,
        )
        for index, (title, system, operation, detail, reversible) in enumerate(templates, start=1)
    )
    return WorkflowPlan(
        workflow_type=f"{case.task_type}:{action}",
        name=_WORKFLOW_NAMES.get(action, "Case resolution workflow"),
        objective=customer_goal,
        steps=steps,
        compensation=_COMPENSATION.get(
            action,
            "Stop remaining steps, preserve completed receipts, and route the case to operations.",
        ),
    )


def _render_detail(template: str, case: CustomerCase, proposal: AgentProposal) -> str:
    return template.format(
        customer_id=case.customer_id,
        amount=f"${proposal.amount:,.2f}",
        task_type=case.task_type.replace("_", " "),
    )


# Each operation represents a narrow provider adapter in production. The demo executor creates
# deterministic provider receipts for the same contract without pretending to call external systems.
_WORKFLOW_TEMPLATES: dict[str, tuple[tuple[str, str, str, str, bool], ...]] = {
    "replacement": (
        (
            "Reserve replacement inventory",
            "Inventory",
            "reserve_replacement",
            "Reserve an eligible unit for {customer_id}.",
            True,
        ),
        (
            "Create replacement order",
            "Fulfillment",
            "create_replacement_order",
            "Create a zero-charge replacement for the {task_type} case.",
            True,
        ),
        (
            "Open quality signal",
            "Quality",
            "open_quality_signal",
            "Attach the failure evidence to the product quality queue.",
            False,
        ),
        (
            "Send tracking and return guidance",
            "Customer communications",
            "send_replacement_notice",
            "Send tracking and return instructions to {customer_id}.",
            False,
        ),
    ),
    "reship": (
        (
            "Validate fulfillment exception",
            "Order management",
            "validate_fulfillment_exception",
            "Confirm the missing-delivery or shipment exception for {customer_id}.",
            False,
        ),
        (
            "Reserve reship inventory",
            "Inventory",
            "reserve_reship_inventory",
            "Reserve only the missing item or quantity.",
            True,
        ),
        (
            "Create priority shipment",
            "Fulfillment",
            "create_priority_reship",
            "Create a tracked replacement shipment at no customer charge.",
            True,
        ),
        (
            "Send recovery update",
            "Customer communications",
            "send_reship_notice",
            "Send the recovery timeline and tracking reference.",
            False,
        ),
    ),
    "exchange": (
        (
            "Reserve correct variant",
            "Inventory",
            "reserve_exchange_variant",
            "Reserve the verified correct SKU or variant.",
            True,
        ),
        (
            "Create prepaid return",
            "Returns",
            "create_exchange_return",
            "Generate a prepaid return authorization for the incorrect item.",
            True,
        ),
        (
            "Create exchange shipment",
            "Fulfillment",
            "create_exchange_shipment",
            "Ship the reserved correct variant to {customer_id}.",
            True,
        ),
        (
            "Send exchange instructions",
            "Customer communications",
            "send_exchange_notice",
            "Send return and replacement tracking in one message.",
            False,
        ),
    ),
    "ship_missing_part": (
        (
            "Reserve component",
            "Parts inventory",
            "reserve_missing_component",
            "Reserve the exact missing component verified by packing evidence.",
            True,
        ),
        (
            "Create component shipment",
            "Fulfillment",
            "create_component_shipment",
            "Create a tracked component-only shipment.",
            True,
        ),
        (
            "Update order completeness",
            "Order management",
            "update_order_completeness",
            "Record the recovered order component for future support context.",
            False,
        ),
        (
            "Send installation guidance",
            "Customer communications",
            "send_component_guidance",
            "Send tracking plus product-specific installation guidance.",
            False,
        ),
    ),
    "refund": (
        (
            "Lock payment transaction",
            "Payments",
            "lock_payment_transaction",
            "Lock the exact verified transaction against a second adjustment.",
            True,
        ),
        (
            "Issue payment refund",
            "Payments",
            "issue_refund",
            "Issue {amount} to the original payment method.",
            False,
        ),
        (
            "Write credit memo",
            "Finance ledger",
            "write_credit_memo",
            "Post the refund reference and reconciliation entry.",
            False,
        ),
        (
            "Notify customer",
            "Customer communications",
            "send_refund_notice",
            "Send the amount, payment reference, and expected settlement timing.",
            False,
        ),
    ),
    "partial_refund": (
        (
            "Create bounded adjustment",
            "Payments",
            "create_partial_adjustment",
            "Prepare a {amount} adjustment tied to the evidence-qualified remedy.",
            True,
        ),
        (
            "Issue partial refund",
            "Payments",
            "issue_partial_refund",
            "Issue {amount} to the original payment method.",
            False,
        ),
        (
            "Record retained-product agreement",
            "Order management",
            "record_keep_agreement",
            "Record the remedy and retained-product terms.",
            False,
        ),
        (
            "Notify customer",
            "Customer communications",
            "send_adjustment_notice",
            "Send the approved adjustment and case reference.",
            False,
        ),
    ),
    "store_credit": (
        (
            "Validate account eligibility",
            "Customer ledger",
            "validate_credit_eligibility",
            "Confirm {customer_id} can receive the bounded account credit.",
            False,
        ),
        (
            "Issue account credit",
            "Customer ledger",
            "issue_store_credit",
            "Issue {amount} as a single-use account credit.",
            False,
        ),
        (
            "Attach expiry and scope",
            "Policy service",
            "attach_credit_terms",
            "Apply the approved expiry and purchase scope.",
            True,
        ),
        (
            "Notify customer",
            "Customer communications",
            "send_credit_notice",
            "Send the credit value, terms, and case reference.",
            False,
        ),
    ),
    "warranty_repair": (
        (
            "Create warranty authorization",
            "Warranty",
            "create_repair_authorization",
            "Create the evidence-backed repair authorization for {customer_id}.",
            True,
        ),
        (
            "Reserve repair capacity",
            "Service network",
            "reserve_repair_capacity",
            "Reserve the appropriate technician or depot route.",
            True,
        ),
        (
            "Create prepaid logistics",
            "Returns",
            "create_repair_logistics",
            "Generate insured prepaid logistics for the product.",
            True,
        ),
        (
            "Send service timeline",
            "Customer communications",
            "send_repair_timeline",
            "Send authorization, logistics, and service-level targets.",
            False,
        ),
    ),
    "guided_troubleshooting": (
        (
            "Select verified diagnostic",
            "Knowledge service",
            "select_diagnostic_playbook",
            "Select the product and symptom-specific diagnostic playbook.",
            False,
        ),
        (
            "Start guided session",
            "Support automation",
            "start_guided_session",
            "Start a guided troubleshooting session for {customer_id}.",
            True,
        ),
        (
            "Capture diagnostic result",
            "Device diagnostics",
            "capture_diagnostic_result",
            "Persist each confirmed diagnostic observation.",
            False,
        ),
        (
            "Set follow-up trigger",
            "Case management",
            "set_followup_trigger",
            "Escalate automatically if the symptom persists after the guided steps.",
            True,
        ),
    ),
    "safety_escalation": (
        (
            "Create safety incident",
            "Product safety",
            "create_safety_incident",
            "Create a priority incident with the supplied safety evidence.",
            False,
        ),
        (
            "Send stop-use notice",
            "Customer communications",
            "send_stop_use_notice",
            "Send immediate no-use and isolation guidance to {customer_id}.",
            False,
        ),
        (
            "Arrange safe recovery",
            "Hazmat logistics",
            "arrange_safe_recovery",
            "Arrange compliant collection or isolation logistics.",
            True,
        ),
        (
            "Place product signal",
            "Quality",
            "place_product_safety_signal",
            "Link the incident to product and batch monitoring.",
            False,
        ),
        (
            "Page safety owner",
            "Incident management",
            "page_safety_owner",
            "Page the designated human safety owner with the complete summary.",
            False,
        ),
    ),
    "seller_investigation": (
        (
            "Preserve claim evidence",
            "Trust and safety",
            "preserve_claim_evidence",
            "Freeze the submitted product, seller, and order evidence.",
            False,
        ),
        (
            "Hold seller settlement",
            "Marketplace ledger",
            "hold_seller_settlement",
            "Place a reversible hold on the affected seller settlement.",
            True,
        ),
        (
            "Open seller investigation",
            "Trust and safety",
            "open_seller_investigation",
            "Create a linked seller integrity investigation.",
            False,
        ),
        (
            "Create customer remedy",
            "Order management",
            "create_marketplace_remedy",
            "Create the approved customer recovery path without destroying evidence.",
            True,
        ),
        (
            "Notify integrity analyst",
            "Incident management",
            "notify_integrity_analyst",
            "Send the complete evidence summary to the assigned integrity analyst.",
            False,
        ),
    ),
    "cost_containment": (
        (
            "Create recovery snapshot",
            "Infrastructure inventory",
            "create_recovery_snapshot",
            "Create a final recovery point for the verified idle resource group.",
            False,
        ),
        (
            "Schedule bounded shutdown",
            "Resource controller",
            "schedule_idle_resource_shutdown",
            "Schedule the dependency-free resource group for shutdown after owner confirmation.",
            True,
        ),
        (
            "Install anomaly guardrail",
            "Cost control",
            "create_cost_anomaly_guardrail",
            "Create a budget alert for the same owner and resource classification.",
            True,
        ),
        (
            "Send savings and recovery plan",
            "Customer communications",
            "send_cost_containment_notice",
            "Send the verified waste, expected savings, shutdown time, and recovery reference.",
            False,
        ),
    ),
    "rollback_deployment": (
        (
            "Freeze failed release",
            "Deployment controller",
            "freeze_failed_release",
            "Stop additional rollout of the failing immutable artifact.",
            True,
        ),
        (
            "Restore last healthy artifact",
            "Deployment controller",
            "restore_healthy_release",
            "Deploy the signed, schema-compatible previous release.",
            True,
        ),
        (
            "Run recovery health gates",
            "Observability",
            "verify_service_recovery",
            "Verify error rate, latency, saturation, and dependency health.",
            False,
        ),
        (
            "Open root-cause record",
            "Change management",
            "open_deployment_rca",
            "Preserve the failed release, health evidence, and rollback receipt.",
            False,
        ),
        (
            "Notify service owners",
            "Customer communications",
            "send_recovery_notice",
            "Send recovery evidence and the follow-up investigation reference.",
            False,
        ),
    ),
    "least_privilege_fix": (
        (
            "Revalidate policy simulation",
            "Authorization service",
            "revalidate_policy_simulation",
            "Confirm the exact resource and action delta remains wildcard-free.",
            False,
        ),
        (
            "Stage scoped policy change",
            "Identity management",
            "stage_least_privilege_policy",
            "Stage only the evidence-derived resource-level permission.",
            True,
        ),
        (
            "Apply owner-approved grant",
            "Identity management",
            "apply_least_privilege_grant",
            "Apply the staged grant after identity-owner approval.",
            True,
        ),
        (
            "Verify allowed and denied paths",
            "Authorization service",
            "verify_policy_boundaries",
            "Prove the required read succeeds while unrelated access remains denied.",
            False,
        ),
        (
            "Send access receipt",
            "Customer communications",
            "send_access_recovery_notice",
            "Send the exact policy delta and verification evidence.",
            False,
        ),
    ),
    "database_capacity_recovery": (
        (
            "Provision temporary read capacity",
            "Database control plane",
            "provision_temporary_read_capacity",
            "Provision the bounded read capacity from the validated plan.",
            True,
        ),
        (
            "Rebalance read traffic",
            "Database routing",
            "rebalance_read_traffic",
            "Shift eligible read traffic while preserving consistency boundaries.",
            True,
        ),
        (
            "Verify latency recovery",
            "Observability",
            "verify_database_recovery",
            "Verify latency, errors, locks, replication health, and saturation.",
            False,
        ),
        (
            "Attach automatic expiry",
            "Capacity control",
            "schedule_capacity_expiry",
            "Expire temporary capacity after the approved recovery window.",
            True,
        ),
    ),
    "traffic_stabilization": (
        (
            "Apply bounded retry policy",
            "Traffic control",
            "apply_retry_backoff_policy",
            "Apply the load-tested backoff and jitter policy to affected clients.",
            True,
        ),
        (
            "Activate queue protection",
            "Request queue",
            "activate_queue_protection",
            "Protect accepted requests with the validated queue limit.",
            True,
        ),
        (
            "Verify completion rate",
            "Observability",
            "verify_traffic_recovery",
            "Verify throttle rate, completion, duplicate suppression, and queue depth.",
            False,
        ),
        (
            "Set automatic rollback threshold",
            "Traffic control",
            "set_traffic_rollback_threshold",
            "Rollback the mitigation if errors exceed the validated boundary.",
            True,
        ),
    ),
    "security_containment": (
        (
            "Seal forensic evidence",
            "Security audit",
            "seal_forensic_evidence",
            "Preserve identity, session, and access evidence before changing credentials.",
            False,
        ),
        (
            "Revoke suspicious session",
            "Identity management",
            "revoke_suspicious_session",
            "Revoke only the verified suspicious privileged session.",
            False,
        ),
        (
            "Rotate affected credential",
            "Secrets management",
            "rotate_compromised_credential",
            "Rotate the affected credential and preserve the break-glass path.",
            False,
        ),
        (
            "Isolate affected workload",
            "Security control",
            "isolate_affected_workload",
            "Apply the incident plan's scoped network and permission isolation.",
            True,
        ),
        (
            "Open security incident",
            "Incident management",
            "open_security_incident",
            "Create the incident with evidence chain, actions, and assigned owner.",
            False,
        ),
    ),
    "isolated_restore": (
        (
            "Create isolated recovery target",
            "Recovery service",
            "create_isolated_restore_target",
            "Create a target that cannot overwrite current production data.",
            True,
        ),
        (
            "Restore immutable recovery point",
            "Backup service",
            "restore_verified_backup",
            "Restore the checksum-verified recovery point into isolation.",
            True,
        ),
        (
            "Run integrity verification",
            "Data verification",
            "verify_restored_data",
            "Verify schema, row counts, referential integrity, and recovery gap.",
            False,
        ),
        (
            "Create promotion request",
            "Change management",
            "create_restore_promotion_request",
            "Prepare the validated restore for accountable owner approval.",
            True,
        ),
        (
            "Send recovery evidence",
            "Customer communications",
            "send_restore_evidence",
            "Send the recovery point, verification results, and promotion request.",
            False,
        ),
    ),
    "quota_adjustment": (
        (
            "Revalidate calculated need",
            "Capacity service",
            "revalidate_quota_need",
            "Confirm observed demand, launch window, and regional capacity.",
            False,
        ),
        (
            "Request bounded temporary quota",
            "Quota service",
            "request_temporary_quota",
            "Request only the evidence-derived increment.",
            True,
        ),
        (
            "Attach budget controls",
            "Cost control",
            "attach_quota_budget_controls",
            "Create the approved cost alert before the quota becomes active.",
            True,
        ),
        (
            "Schedule quota expiry",
            "Quota service",
            "schedule_quota_expiry",
            "Return the account to its prior limit after the approved window.",
            True,
        ),
        (
            "Send capacity receipt",
            "Customer communications",
            "send_quota_notice",
            "Send the approved limit, expiry, budget, and monitoring references.",
            False,
        ),
    ),
    "deny": (
        (
            "Record evidence-based denial",
            "Case management",
            "record_denial",
            "Record why the requested remedy is not supported by current evidence.",
            False,
        ),
        (
            "Create appeal path",
            "Case management",
            "create_appeal_path",
            "Create a route for {customer_id} to provide the missing evidence.",
            True,
        ),
        (
            "Send decision explanation",
            "Customer communications",
            "send_denial_explanation",
            "Send the decision, supporting facts, and appeal requirements.",
            False,
        ),
    ),
}


_WORKFLOW_NAMES = {
    "replacement": "Replacement recovery",
    "reship": "Fulfillment recovery",
    "exchange": "Verified product exchange",
    "ship_missing_part": "Missing component recovery",
    "refund": "Payment reversal",
    "partial_refund": "Retain-and-adjust resolution",
    "store_credit": "Bounded account credit",
    "warranty_repair": "Warranty service recovery",
    "guided_troubleshooting": "Guided product recovery",
    "safety_escalation": "Product safety response",
    "seller_investigation": "Marketplace integrity response",
    "cost_containment": "Verified cost containment",
    "rollback_deployment": "Safe release rollback",
    "least_privilege_fix": "Least-privilege access recovery",
    "database_capacity_recovery": "Reversible database capacity recovery",
    "traffic_stabilization": "API traffic stabilization",
    "security_containment": "Privileged credential containment",
    "isolated_restore": "Isolated data recovery",
    "quota_adjustment": "Bounded temporary quota adjustment",
    "deny": "Evidence-based denial and appeal",
}


_COMPENSATION = {
    "replacement": "Cancel unshipped fulfillment and release reserved inventory.",
    "reship": "Cancel the unshipped reship and release reserved inventory.",
    "exchange": "Cancel unshipped legs and release the correct variant reservation.",
    "ship_missing_part": "Cancel the unshipped component and release the parts reservation.",
    "refund": "Do not retry the refund without the same idempotency key; reconcile the provider receipt.",
    "partial_refund": "Do not duplicate the adjustment; reconcile the payment and ledger receipts.",
    "store_credit": "Void unused credit and retain the audit trail if a downstream step fails.",
    "warranty_repair": "Cancel unused logistics and release the service reservation.",
    "guided_troubleshooting": "Close the guided session and preserve captured diagnostics for escalation.",
    "safety_escalation": "Safety notifications remain active; escalate any failed recovery step to the safety owner.",
    "seller_investigation": "Keep preserved evidence and route any failed financial hold to an integrity analyst.",
    "cost_containment": "Restart the preserved resource from the recovery snapshot if a verified dependency appears.",
    "rollback_deployment": "Reapply the failed release only after its root cause is corrected and every health gate passes.",
    "least_privilege_fix": "Remove the staged grant and restore the prior policy if boundary verification fails.",
    "database_capacity_recovery": "Remove temporary capacity after traffic is safely rebalanced to the prior topology.",
    "traffic_stabilization": "Restore the previous retry policy automatically if completion or error thresholds regress.",
    "security_containment": "Do not restore revoked access automatically; the incident commander owns recovery authorization.",
    "isolated_restore": "Delete only the isolated target if validation fails; never modify the current production dataset.",
    "quota_adjustment": "Return to the prior quota at expiry or immediately if budget or abuse controls trigger.",
    "deny": "Reopen the case if new required evidence is submitted through the appeal path.",
}
